listen:
  port: 4040

namespaces:
  - name: nginx
    source:
      syslog:
        listen_address: unix:///tmp/syslog.sock
        tags:
          - ""
    format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\""
